### PR TITLE
Add some UI tests

### PR DESCRIPTION
**Pull request by gjmooney**
#7 Add some UI tests.

### CODE REVIEW

**Comment by gjmooney** [comment]
please update snapshots

**Comment by gjmooney** [comment]
please update snapshots

**Comment by jtpio** [comment]
Looks like the snapshot update workflows is failing: https://github.com/TileDB-Inc/jupyter-iframe-commands/actions/runs/12122527111/job/33795905340

We will probably need to first fix the workflow and have the changes available on the `main` since that workflow runs from `main`.

Otherwise in the meantime we could grab the snapshots from the playwright report for this PR, and commit them directly.

**Comment by gjmooney** [comment]
> Looks like the snapshot update workflows is failing: https://github.com/TileDB-Inc/jupyter-iframe-commands/actions/runs/12122527111/job/33795905340
> 
> We will probably need to first fix the workflow and have the changes available on the `main` since that workflow runs from `main`.
> 
> Otherwise in the meantime we could grab the snapshots from the playwright report for this PR, and commit them directly.

Yea I'm fighting with this on my fork right now, I didn't want to keep spamming this repo :melting_face:

**Comment by gjmooney** [comment]
please update snapshots

**Comment by jtpio** [comment]
Kicking CI after the snapshot update.

**Comment by jtpio** [comment]
Looking at the UI tests report, it seems the snapshot is taken a bit too soon before JupyterLab has time to load properly:

[jupyter-iframe-commands-ui-tests.webm](https://github.com/user-attachments/assets/0e00a669-93c0-48a6-b04b-af6b2c9f540d)

Maybe we can introduce an artificial delay, or look for a specific element in the JupyterLab Iframe before taking the snapshot (which would be more robust than relying on an arbitrary timeout).

**Comment by gjmooney** [comment]
> Maybe we can introduce an artificial delay, or look for a specific element in the JupyterLab Iframe before taking the snapshot (which would be more robust than relying on an arbitrary timeout).

I'm attempting to wait for the splash screen to be gone before taking the snapshot https://github.com/TileDB-Inc/jupyter-iframe-commands/blob/ab94082779f4574533b54d948b8d7cac2887643c/ui-tests/tests/hostpage-tests.spec.ts#L3-L28 but that's not doing it apparently.

**Comment by jtpio** [comment]
Indeed, and this also looks similar to what Galata does by default: https://github.com/jupyterlab/jupyterlab/blob/a0733bf0ccc29fe8830b89cf557edfa14ffc9fd8/galata/src/fixtures.ts#L352-L355

**Comment by gjmooney** [comment]
please update snapshots

**Pull request merged**
